### ISSUE TITLE
How to submit tests

### ISSUE THREAD

**Issue by pasumps1** [ModernAppsNinja/vspheretanzu101_vt7301#1172]
I am getting error . where i have to check

**Comment by pasumps1** [comment]
![image (189)](https://user-images.githubusercontent.com/71697226/123769740-3ac58400-d8e7-11eb-8924-199a8ef53684.png)

**Comment by afewell** [comment]
Hi @pasumps1 it looks like you may not have enrolled in the course or your enrollment may not have processed correctly. I think this is happening because when you enroll, it creates the section in your member page where it adds the test results and since that process never completed successfully it is erring. 

If you could try the enrollment for the course again by posting a file named yourgithubusername.yml to the [https://github.com/ModernAppsNinja/vspheretanzu101_vt7301/tree/main/static/admin/userdata/registered_members](https://github.com/ModernAppsNinja/vspheretanzu101_vt7301/tree/main/static/admin/userdata/registered_members) directory that should fix the issue and then you should be able to resubmit the tests and cert request. Please let me know if you have any problems with the enrollment process, thanks!
